s/\bJudiciarv\b/Judiciary/ig
s/\bTvdings\b/Tydings/g
s/\bbv\b/by/g
s/\banv\b/any/g
s/\bdenved\b/derived/g
s/\bm\b/in/g
s/\bpiopose\b/propose/g
s/\bwhioh\b/which/g
s/\beto.\b/etc./g
s/\bwit inn\b/within/g
s/\bwrorks\b/works/g
s/\bLnited\b/United/g
s/\bsolelv\b/solely/g
s/\blavs\b/lays/g
s/\bArmv\b/Army/g
s/\biniured\b/injured/g
s/\bDedares\b/Declares/ig
s/\bcrcp\b/crop/ig
s/\bWilev\b/Wiley/ig
s/\bdomestio\b/domestic/ig
